version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    command: npm start
    ports:
      - "3333:3333"
  postgres:
    image: postgres:10.5-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
