version: '3'
services:
  api:
    build: api
    depends_on:
      - postgres
    command: npm start
    ports:
    - "3333:3333"
    - "9229:9229"
  postgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
